name: SP_Essential
version: '${project.version}'
main: SPEssential.SPEssential
api-version: 1.19
authors: [ Gnaris ]
depend:
  - SP_Database
commands:
  gamemode:
    description: "Change le mode jeu"
    aliases: [gm]
  enderchest:
    description: "Ouvre l'enderchest"
    aliases: [ec]
  fly:
    description: "Voler dans les airs"
  heal:
    description: "Soigner quelqu'un"
  feed:
    description: "Rassasié quelqu'un"
  kill:
    description: "Tue quelqu'un"
  vanish:
    description: "Mode invisible"
    aliases: [v]
  message:
    description: "Envoie un message privé à quelqu'un"
    aliases: [w, mp, send, m, msg]
  spymessage:
    description: "Espionne les messages privés"
    aliases: [spy, spymp, spymsg]
  teleport:
    description: "Teleportation"
    aliases: [tp]
  teleportto:
    description: "Demande de téléportation"
    aliases: [tpa, tpto, tpt]
  teleportaccept:
    description: "Accepte la demande de téléportation"
    aliases: [tpaccept, tpyes]
  teleportdeny:
    description: "Refuse la demande de téléportation"
    aliases: [tpdeny, tpno]
  invsee:
    description: "Voir l'inventaire d'un joueur"
  spawn:
    description: "Se téléporter au spawn"
  setspawn:
    description: "Défini un nouveau spawn"
  warp:
    description: "Se téléporter dans un warp"
  setwarp:
    description: "Ajouter un nouveau warp"
  deletewarp:
    description: "Supprimer un warp"
  back:
    description: "Revenir à la dernière position"
  hat:
    description: "Porter un nouveau chapeau"
  condense:
    description: "Condense les minerais"
  craft:
    description: "Ouvre la table de craft"
permissions:
  sperias.essential.command.gamemode:
    description: "Command /gamemode"
  sperias.essential.command.enderchest:
    description: "Command /enderchest"
    children: [sperias.essential.command.enderchest.me]
  sperias.essential.command.fly:
    description: "Command /fly"
  sperias.essential.command.heal:
    description: "Command /heal"
    children: [sperias.essential.command.heal.me]
  sperias.essential.command.feed:
    description: "Command /feed"
    children: [sperias.essential.command.feed.me]
  sperias.essential.command.kill:
    description: "Command /kill"
    children: [ sperias.essential.command.kill.me]
  sperias.essential.command.vanish:
    description: "Command /vanish"
  sperias.essential.command.spymessage:
    description: "Command /spymessage"
  sperias.essential.command.tp:
    description: "Command /tp"
  sperias.essential.command.invsee:
    description: "Command /invsee"
  sperias.essential.invsee.takeitem:
    description: "Prendre l'item du joueur dans son inventaire"
  sperias.essential.command.setspawn:
    description: "Command /setspawn"
  sperias.essential.command.setwarp:
    description: "Command /setwarp"
  sperias.essential.command.deletewarp:
    description: "Command /deletewarp"
  sperias.essential.command.back:
    description: "Command /back"
  sperias.essential.command.hat:
    description: "Command /hat"
  sperias.essential.command.condense:
    description: "Command /condense"
  sperias.essential.command.craft:
    description: "Command /craft"